from __future__ import annotations

import os
import numpy as np
import ctypes
import joblib
from typing import Optional

from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.utils.validation import check_is_fitted

from ._oqboost import (
    OQBoostTree,
    OQBoostContext,
    predict_ensemble,
)

class OQBoostRegressor(BaseEstimator, RegressorMixin):
    """Oblique Gradient-Boosted Decision Trees for Regression.

    Parameters
    ----------
    loss : str, default="squared_error"
        The loss function to be optimized. "squared_error" for MSE,
        "absolute_error" for MAE, "huber" for Huber loss.
    huber_delta : float, default=1.0
        The threshold at which to scale the Huber loss.
    n_estimators : int, default=1000
        Number of boosting rounds.
    learning_rate : float, default=0.03
        Shrinkage parameter to control the contribution of each tree.
    max_depth : int, default=6
        Maximum depth of each tree.
    reg_lambda : float, default=1.0
        L2 regularization on split gains and leaf values.
    subsample : float, default=0.8
        Fraction of samples to randomly select for each round.
    early_stopping_rounds : int or None, default=50
        Patience rounds for early stopping based on validation score.
    random_state : int or None, default=None
        Random state for reproducibility.
    verbose : bool, default=False
        Whether to print verbose logs during training.
    cat_features : list or None, default=None
        Indices or names of categorical features.
    inherited_rp_ratio : float, default=1.0
        Fraction of oblique split candidates generated by parent weight inheritance.
    mutation_rate : float, default=0.1
        Base scale for axis mutation (Strategy A).
    mutation_strength : float, default=0.5
        Base weight for new-axis borrowing (Strategy B).
    pobs : bool, default=False
        Whether to inject pobs candidates into split tournaments.
    goss : bool, default=False
        Whether to use GOSS row-sampling.
    goss_top_rate : float, default=0.2
        GOSS top gradient retention rate.
    goss_other_rate : float, default=0.1
        GOSS lower gradient sample rate.
    reg_alpha : float, default=0.0
        L1 regularization parameter.
    gamma : float, default=0.0
        Minimum split loss threshold.
    min_child_weight : float, default=1.0
        Minimum sum of instance Hessian in a child node.
    max_leaves : int or None, default=None
        Maximum number of leaves per tree.
    max_bin : int, default=255
        Maximum number of bins to bucket continuous values.
    colsample_bynode : float, default=1.0
        Feature subsampling ratio per node split.
    """

    def __init__(
        self,
        loss:                  str   = "squared_error",
        huber_delta:           float = 1.0,
        n_estimators:          int   = 1000,
        learning_rate:         float = 0.03,
        max_depth:             int   = 6,
        reg_lambda:            float = 1.0,
        subsample:             float = 0.8,
        early_stopping_rounds: int | None = 50,
        random_state:          int | None = None,
        verbose:               bool  = False,
        cat_features:          list | None = None,
        inherited_rp_ratio:    float = 1.0,
        mutation_rate:         float = 0.1,
        mutation_strength:     float = 0.5,
        pobs:                  bool  = False,
        goss:                  bool  = False,
        goss_top_rate:         float = 0.2,
        goss_other_rate:       float = 0.1,
        reg_alpha:             float = 0.0,
        gamma:                 float = 0.0,
        min_child_weight:      float = 1.0,
        max_leaves:            int | None = None,
        max_bin:               int = 255,
        colsample_bynode:      float = 1.0,
    ):
        self.loss                  = loss
        self.huber_delta           = huber_delta
        self.n_estimators          = n_estimators
        self.learning_rate         = learning_rate
        self.max_depth             = max_depth
        self.reg_lambda            = reg_lambda
        self.subsample             = subsample
        self.early_stopping_rounds = early_stopping_rounds
        self.random_state          = random_state
        self.verbose               = verbose
        self.cat_features          = cat_features
        self.inherited_rp_ratio    = inherited_rp_ratio
        self.mutation_rate         = mutation_rate
        self.mutation_strength     = mutation_strength
        self.pobs                  = pobs
        self.goss                  = goss
        self.goss_top_rate         = goss_top_rate
        self.goss_other_rate       = goss_other_rate
        self.reg_alpha             = reg_alpha
        self.gamma                 = gamma
        self.min_child_weight      = min_child_weight
        self.max_leaves            = max_leaves
        self.max_bin               = max_bin
        self.colsample_bynode      = colsample_bynode
        self.feature_names_in_     = None

    def _prepare_data(self, X, is_fit=False):
        import pandas as pd
        if not isinstance(X, pd.DataFrame):
            if hasattr(X, "values"):
                X = X.values
            return np.asarray(X, dtype=np.float32)

        X_prep = X.copy()

        if is_fit:
            self.feature_names_in_ = list(X.columns)
            self._cat_mappings_ = {}

        cat_cols = []
        if self.cat_features:
            for cf in self.cat_features:
                if isinstance(cf, (int, np.integer)):
                    if 0 <= cf < len(X.columns):
                        cat_cols.append(X.columns[cf])
                elif cf in X.columns:
                    cat_cols.append(cf)
        else:
            for col in X.columns:
                if isinstance(X[col].dtype, pd.CategoricalDtype) or X[col].dtype == object:
                    cat_cols.append(col)

        for col in cat_cols:
            if is_fit:
                unique_vals = X_prep[col].dropna().unique()
                mapping = {val: idx for idx, val in enumerate(unique_vals)}
                self._cat_mappings_[col] = mapping
            else:
                mapping = self._cat_mappings_.get(col, {})

            # Map categories to float codes, NaNs stay NaN
            codes = X_prep[col].map(mapping).astype(np.float32)
            X_prep[col] = codes

        return X_prep.values.astype(np.float32)

    def fit(
        self,
        X,
        y,
        eval_set: list[tuple] | None = None,
        sample_weight=None,
    ) -> OQBoostRegressor:
        """Fit the regressor.

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
        y : array-like of shape (n_samples,)
        eval_set : list of (X_val, y_val) tuples, optional
            First tuple is used for early stopping and validation metrics.
        sample_weight : array-like of shape (n_samples,), optional
            Individual weights for each sample.
        """
        X = self._prepare_data(X, is_fit=True)
        y = np.asarray(y, dtype=np.float32)

        self.n_features_in_ = X.shape[1]

        if sample_weight is not None:
            sample_weight = np.asarray(sample_weight, dtype=np.float32)
            if sample_weight.ndim != 1 or len(sample_weight) != X.shape[0]:
                raise ValueError("sample_weight must be a 1D array of length N.")

        D_num = self._resolve_D_num(X.shape[1])

        X_val, y_val = None, None
        if eval_set:
            X_val, y_val = eval_set[0]
            X_val = self._prepare_data(X_val, is_fit=False)
            y_val = np.asarray(y_val, dtype=np.float32)

        self._fit_core(X, y, X_val, y_val, D_num, sample_weight=sample_weight)
        return self

    def predict(self, X) -> np.ndarray:
        check_is_fitted(self, "trees_")
        X = self._prepare_data(X, is_fit=False)
        X = np.ascontiguousarray(X, dtype=np.float32)
        if getattr(self, "_col_perm_", None) is not None:
            X = np.ascontiguousarray(X[:, self._col_perm_])
        
        F = predict_ensemble(self.trees_, X, 1, self.learning_rate,
                             np.array(self.F_init_, dtype=np.float32))
        return F.ravel()

    def save(self, path: str) -> None:
        """Save the fitted model to disk."""
        joblib.dump(self, path, compress=3)

    @classmethod
    def load(cls, path: str) -> OQBoostRegressor:
        """Load a saved model from disk."""
        return joblib.load(path)

    def get_n_trees(self) -> int:
        """Return the number of trees actually fitted."""
        check_is_fitted(self, "trees_")
        return len(self.trees_)

    def _resolve_cat_idx(self, D: int) -> list[int]:
        if not self.cat_features:
            return []
        cat_idx = set()
        for cf in self.cat_features:
            if isinstance(cf, (int, np.integer)):
                cat_idx.add(int(cf))
            else:
                names = getattr(self, "feature_names_in_", None)
                if names is not None and cf in names:
                    cat_idx.add(names.index(cf))
        return sorted(cat_idx)

    def _resolve_D_num(self, D: int) -> int:
        return D - len(self._resolve_cat_idx(D))

    def _fit_core(self, X, y, X_val, y_val, D_num, sample_weight=None):
        N, D = X.shape
        seed = self.random_state if self.random_state is not None else 42

        cat_idx = self._resolve_cat_idx(D)
        if cat_idx and cat_idx != list(range(D_num, D)):
            perm = [i for i in range(D) if i not in set(cat_idx)] + cat_idx
            self._col_perm_ = np.asarray(perm, dtype=np.intp)
        else:
            self._col_perm_ = None
        if self._col_perm_ is not None:
            X = np.ascontiguousarray(X[:, self._col_perm_])
            if X_val is not None:
                X_val = np.ascontiguousarray(X_val[:, self._col_perm_])

        # Loss-specific F_init
        if self.loss in ("squared_error", "l2"):
            if sample_weight is not None:
                self.F_init_ = [float(np.average(y, weights=sample_weight))]
            else:
                self.F_init_ = [float(np.mean(y))]
        elif self.loss in ("absolute_error", "l1", "huber"):
            if sample_weight is not None:
                # Weighted median approximation
                sorted_idx = np.argsort(y)
                sorted_y = y[sorted_idx]
                sorted_w = sample_weight[sorted_idx]
                cum_w = np.cumsum(sorted_w)
                cutoff = cum_w[-1] / 2.0
                median_idx = np.searchsorted(cum_w, cutoff)
                self.F_init_ = [float(sorted_y[median_idx])]
            else:
                self.F_init_ = [float(np.median(y))]
        else:
            raise ValueError(f"Unknown loss: {self.loss}")

        Fsc   = np.tile(self.F_init_, (N, 1))
        F_val = np.tile(self.F_init_, (X_val.shape[0], 1)) if X_val is not None else None

        rng = np.random.default_rng(seed)

        best_val_loss = float("inf")
        best_trees:   list = []
        no_improv = 0

        self.trees_: list = []

        ctx = OQBoostContext(X, D_num=D_num, max_bin=self.max_bin)
        G_w = np.empty((N, 1), dtype=np.float32)
        H_w = np.empty((N, 1), dtype=np.float32)
        full_idx = np.arange(N, dtype=np.int32)
        try:
            for m in range(self.n_estimators):
                # Compute Gradients & Hessians on Python side
                diff = Fsc - y[:, np.newaxis]
                if self.loss in ("squared_error", "l2"):
                    G_w[:, 0] = diff[:, 0]
                    H_w[:, 0] = 1.0
                elif self.loss in ("absolute_error", "l1"):
                    G_w[:, 0] = np.sign(diff[:, 0])
                    H_w[:, 0] = 1.0
                elif self.loss == "huber":
                    abs_diff = np.abs(diff[:, 0])
                    delta = self.huber_delta
                    G_w[:, 0] = np.where(abs_diff <= delta, diff[:, 0], delta * np.sign(diff[:, 0]))
                    H_w[:, 0] = 1.0

                if sample_weight is not None:
                    G_w *= sample_weight[:, np.newaxis]
                    H_w *= sample_weight[:, np.newaxis]

                # Sampling
                if self.goss:
                    grad_norms = np.abs(G_w[:, 0])
                    top_n = int(self.goss_top_rate * N)
                    other_n = int(self.goss_other_rate * (N - top_n))
                    if top_n > 0 and other_n > 0 and (top_n + other_n) < N:
                        k = N - top_n
                        partitioned_idx = np.argpartition(grad_norms, k)
                        top_idx = partitioned_idx[k:]
                        remaining_idx = partitioned_idx[:k]
                        random_idx = rng.choice(remaining_idx, size=other_n, replace=False)
                        tree_sub = np.concatenate([top_idx, random_idx]).astype(np.int32)
                        scale_factor = (1.0 - self.goss_top_rate) / self.goss_other_rate
                        G_w[random_idx] *= scale_factor
                        H_w[random_idx] *= scale_factor
                    else:
                        tree_sub = full_idx
                elif self.subsample < 1.0:
                    tree_sub = np.flatnonzero(
                        rng.random(N) < self.subsample
                    ).astype(np.int32)
                    if len(tree_sub) < min(N, 1000):
                        tree_sub = full_idx
                else:
                    tree_sub = full_idx

                t, out_pred = ctx.build(
                    G_w, H_w, tree_sub, self.max_depth, self.reg_lambda,
                    inherited_rp_ratio=self.inherited_rp_ratio,
                    mutation_rate=self.mutation_rate,
                    mutation_strength=self.mutation_strength,
                    seed=int(rng.integers(1 << 30)),
                    pobs=getattr(self, "pobs", False),
                    reg_alpha=self.reg_alpha,
                    gamma=self.gamma,
                    min_child_weight=self.min_child_weight,
                    colsample_bynode=self.colsample_bynode,
                    max_leaves=self.max_leaves if self.max_leaves is not None else (1 << self.max_depth),
                )

                self.trees_.append(t)
                Fsc += self.learning_rate * out_pred

                val_str = ""
                if X_val is not None:
                    pred_val = t.predict(X_val)
                    F_val    = F_val + self.learning_rate * pred_val
                    
                    diff_val = F_val - y_val[:, np.newaxis]
                    if self.loss in ("squared_error", "l2"):
                        val_loss = float(np.mean(diff_val[:, 0] ** 2))
                    elif self.loss in ("absolute_error", "l1"):
                        val_loss = float(np.mean(np.abs(diff_val[:, 0])))
                    elif self.loss == "huber":
                        abs_diff_val = np.abs(diff_val[:, 0])
                        delta = self.huber_delta
                        huber_loss = np.where(abs_diff_val <= delta, 0.5 * (diff_val[:, 0] ** 2), delta * (abs_diff_val - 0.5 * delta))
                        val_loss = float(np.mean(huber_loss))
                        
                    val_str  = f" | ValLoss={val_loss:.4f}"

                    if val_loss < best_val_loss:
                        best_val_loss = val_loss
                        no_improv     = 0
                        best_trees    = list(self.trees_)
                    else:
                        no_improv += 1

                if self.verbose:
                    diff_train = Fsc - y[:, np.newaxis]
                    train_loss = float(np.mean(diff_train[:, 0] ** 2))
                    print(
                        f"  [OQBoost Regressor] Round {m+1:3d} | TrainMSE={train_loss:.4f}{val_str}"
                    )

                if X_val is not None and self.early_stopping_rounds is not None:
                    if no_improv >= self.early_stopping_rounds:
                        if self.verbose:
                            print(f"  [OQBoost Regressor] Early stopping at round {m+1}")
                        self.trees_ = best_trees
                        break
        finally:
            ctx.close()
